routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('bus', 'BusController');

Route::resource('ruta', 'RutaController');


Route::resource('cotizacion', 'CotizacionController');

Route::get('/inicioCotizar', 'CotizacionController@inicioCotizar');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Bus.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Bus extends Model
{
    protected $table = 'bus';
    protected $fillable = ['modelo', 'nombre_conductor'];

    public function ruta()
    {
        return $this->hasMany('App\Ruta');
    }
}

app/Ruta.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ruta extends Model
{
    protected $table = 'ruta';
    protected $fillable = ['nombre_ruta', 'origen_ciudad', 'destino_ciudad', 'bus_Id', 'valor_pasaje'];

    public function bus()
    {
        return $this->belongsTo('App\Bus');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BusController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Bus;

class BusController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $bus = bus::orderBy('id', 'ASC')->get();
        return view('bus.index',compact('bus'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('bus.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        bus::create($request->all());
        return redirect()->route('bus.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $bus = bus::find($id);
        return view('bus.edit', compact('bus'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        bus::find($id)->update($request->all());
        return redirect()->route('bus.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        bus::find($id)->delete();
        return redirect()->route('bus.index')->with('success','Eliminado');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CotizacionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ruta;
use App\Classes\CotizacionService;

class CotizacionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $origenes = ruta::distinct()->select('origen_ciudad')->orderBy('origen_ciudad', 'ASC')->get();
        $destinos = ruta::distinct()->select('destino_ciudad')->orderBy('destino_ciudad', 'ASC')->get();

        return view('cotizacion.index',
            [
                "origenes" => $origenes, 
                "destinos" => $destinos
            ]
        );
    }

    public function inicioCotizar (Request $request) {

        $service = new CotizacionService();
        $result = $service->cotizar($request->origen, $request->destino);

        $response = [
            'result' => $result
        ];

        return response()->json($response, 200);
    }

}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/RutaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Ruta;
use App\Bus;

class RutaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $ruta = ruta::orderBy('id', 'ASC')->get();
        return view('ruta.index',compact('ruta'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // We need a list of busses to create a route
        $buses = bus::orderBy('id', 'ASC')->get();
        return view('ruta.create', ["buses" => $buses]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        ruta::create($request->all());
        return redirect()->route('ruta.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $ruta = ruta::find($id);
        return view('ruta.edit', compact('ruta'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        ruta::find($id)->update($request->all());
        return redirect()->route('ruta.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        ruta::find($id)->delete();
        return redirect()->route('ruta.index')->with('success','Eliminado');
    }
}

resources/views/Bus/create.blade.php
@extends('layouts.app')
@section('content')
<div class="col-md-5 col-md-offset-1">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Nuevo bus</h3>
        </div>
        <div class="table-container">
            <form method="POST" action="{{ route('bus.store') }}"  role="form">
                {{ csrf_field() }}
                <table class="table">
                    <tr>
                        <th>Modelo</th>
                        <td>
                            <input type="number" name="modelo" id="modelo" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <th>Nombre Conductor</th>
                        <td>
                            <input type="text" name="nombre_conductor" id="nombre_conductor" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-success btn-block">
                                Guardar
                            </button>
                        </td>
                    </tr>

                </table>
            </form>
        </div>

    </div>
    <a href="{{ route('bus.index') }}" class="btn btn-info btn-block w-sm" >Atrás</a>
</div>

@endsection

resources/views/Bus/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="col-md-8 col-md-offset-2">

    @if(Session::has('success'))
    <div class="alert alert-info">
        {{Session::get('success')}}
    </div>
    @endif

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Actualizar bus id = {{ $bus->id }}</h3>
        </div>
        <div class="table-container">
            <form method="POST" action="{{ route('bus.update',$bus->id) }}"  role="form">
                {{ csrf_field() }}
                <input name="_method" type="hidden" value="PATCH">

                <table class="table">
                    <tr>
                        <th>Nombre</th>
                        <td>
                            <input type="number" name="modelo" id="modelo" class="form-control input-sm" value="{{ $bus->modelo }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>
                            <input type="text" name="nombre_conductor" id="nombre_conductor" class="form-control input-sm"  value="{{ $bus->nombre_conductor }}"  >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-primary btn-block">
                                Actualizar
                            </button>
                        </td>
                    </tr>

                </table>
            </form>
        </div>
    </div>
    <a href="{{ route('bus.index') }}" class="btn btn-info btn-block w-sm" >Atrás</a>
</div>

@endsection

resources/views/Bus/index.blade.php
@extends('layouts.app')
@section('content')
<div class="col-md-8 col-md-offset-1">

    <div class="pull-left"><h3>Lista buses</h3></div>
    <div class="pull-right">

        <a href="{{ route('bus.create') }}"> 
            <button class="btn btn-info" >Añadir bus</button>
        </a>

    </div>

    <div class="table-container">
        <table class="table table-bordered table-striped">
            <thead>
                <th>Id</th>
                <th>Modelo</th>
                <th>Conductor</th>
                <th colspan="2">Acciones</th>
            </thead>
            <tbody>
                @if($bus->count())  
                    @foreach($bus as $item)  
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->modelo}}</td>
                        <td>{{$item->nombre_conductor}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{{action('BusController@edit', $item->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a>
                        </td>
                        <td>
                            <form action="{{action('BusController@destroy', $item->id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">

                                <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach 
                @else
                    <tr>
                        <td colspan="4">No hay registros !!</td>
                    </tr>
                @endif
            </tbody>
        </table>
       
    </div>
</div>


@endsection

resources/views/Cotizacion/index.blade.php
@extends('layouts.layout')
@section('content')


<div class="col-md-8 col-md-offset-1">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Cotizacion de rutas</h3>
        </div>
        <div class="table-container">
            <div class="row"></div>

            <div class="row">
                <div class="col-sm-3">
                    <b>Origen</b>
                    <select id="origen">
                    @foreach($origenes as $item)
                        <option>{{ $item->origen_ciudad }}</option>
                    @endforeach
                    </select>

                </div>
                <div class="col-sm-4">
                    <b>Destino</b>
                    <select id="destino">
                    @foreach($destinos as $item)
                        <option>{{ $item->destino_ciudad }}</option>
                    @endforeach
                    </select>

                </div>
                <div class="col-sm-2">

                    <button id="calcular" class="btn btn-success">
                        <span class="glyphicon glyphicon-search"></span>
                        Calcular
                    </button>

                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                        <div id="msg"></div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                        <span class="glyphicon glyphicon-plane"></span>
                        <div id="tripTexto" style="display: inline"></div>
                </div>
            </div>


            <div class="row">
                <div class="col-sm-12">
                        <span class="glyphicon glyphicon-usd"></span>
                        <div id="valorTotal" style="display: inline"></div>
                </div>
            </div>

            <div class="row">
                <div class="col-sm-12">
                        <span class="glyphicon glyphicon-plane"></span>
                        <div id="tripDetallado" style="display: inline"></div>
                </div>
            </div>

        </div>
    </div>
</div>


<script>
$(document).ready(function(){

    $("#calcular").click(function() {

        var origen = $("#origen").val();
        var destino = $("#destino").val();

        if (origen == destino) {
            $("#msg").html("<div class='alert alert-warning'>Ciudad de origen es igual a la Ciudad destino</div>");
        } else {

            $.ajax({
                type: "GET",
                dataType: 'json',
                url: "/inicioCotizar",
                data: {
                    'origen': origen,
                    'destino': destino,
                },
                success: function (data) {

                    var msg = "No se encontro esta ruta";
                    var msgClass = "warning";
                    var valor = "";
                    var tripTexto = "";
                    var tripDetallado = "";

                    data = data.result;

                    if (data.isOk) {

                        valor = 0;

                        // Add origen city to the trip text
                        tripTexto = data.trip[0].origen_ciudad;

                        $.each(data.trip, function(index, current) {
                            valor = parseInt(valor) + parseInt(current.valor_pasaje);

                            // Create the short text for the trip
                            tripTexto += " -> " + current.destino_ciudad;

                            // Create a detail text for the trip
                            tripDetallado += "Desde " + current.origen_ciudad + " hasta " + current.destino_ciudad + " en Bus " + current.bus_Id + " con valor de $" + current.valor_pasaje + ". ";

                        });

                        msgClass = "info";
                        msg = "Ruta encontrada";

                        valor = "Valor pasaje $" + valor;
                    }

                    $("#msg").html("<div class='alert alert-" + msgClass + "' >" +  msg + "</div>");
                    $("#tripTexto").text(tripTexto);
                    $("#valorTotal").text(valor);
                    $("#tripDetallado").text(tripDetallado);
                }
            });
        }
    });

});
</script>

<style>

.row{
    min-height: 50px;
    padding: 2px;
    vertical-align: middle;
}

</style>


@endsection

resources/views/Ruta/create.blade.php
@extends('layouts.app')
@section('content')

<div class="col-md-5 col-md-offset-1">

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Nueva Ruta</h3>
        </div>
        <div class="table-container">

            <form method="POST" action="{{ route('ruta.store') }}"  role="form">
                {{ csrf_field() }}
                <table class="table">

                    <tr>
                        <th>Nombre Ruta</th>
                        <td>
                            <input type="text" name="nombre_ruta" id="nombre_ruta" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <th>Origen</th>
                        <td>
                            <input type="text" name="origen_ciudad" id="origen_ciudad" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <th>Destino</th>
                        <td>
                            <input type="text" name="destino_ciudad" id="destino_ciudad" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <th>Bus</th>
                        <td>
                            <select name="bus_Id">
                                @foreach($buses as $item) 
                                    <option value="{{ $item->id }}">{{ $item->modelo . " - " . $item->nombre_conductor}}</option>
                                @endforeach
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>Pasaje</th>
                        <td>
                            <input type="number" name="valor_pasaje" id="valor_pasaje" class="form-control input-sm" >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-success btn-block">
                                Guardar
                            </button>
                        </td>
                    </tr>

                </table>
            </form>
        </div>

    </div>
    <a href="{{ route('ruta.index') }}" class="btn btn-info btn-block w-sm" >Atrás</a>
</div>

@endsection

resources/views/Ruta/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="col-md-8 col-md-offset-2">

    @if(Session::has('success'))
    <div class="alert alert-info">
        {{Session::get('success')}}
    </div>
    @endif

    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Actualizar ruta id = {{ $ruta->id }}</h3>
        </div>
        <div class="table-container">
            <form method="POST" action="{{ route('ruta.update',$ruta->id) }}"  role="form">
                {{ csrf_field() }}
                <input name="_method" type="hidden" value="PATCH">

                <table class="table">
                    <tr>
                        <th>Nombre ruta</th>
                        <td>
                            <input type="text" name="nombre_ruta" id="nombre_ruta" class="form-control input-sm" value="{{ $ruta->nombre_ruta }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Origen</th>
                        <td>
                            <input type="text" name="origen_ciudad" id="origen_ciudad" class="form-control input-sm" value="{{ $ruta->origen_ciudad }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Destino</th>
                        <td>
                            <input type="text" name="destino_ciudad" id="destino_ciudad" class="form-control input-sm" value="{{ $ruta->destino_ciudad }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Bus_Id</th>
                        <td>
                            <input type="text" name="bus_Id" id="bus_Id" class="form-control input-sm" value="{{ $ruta->bus_Id }}">
                        </td>
                    </tr>
                    <tr>
                        <th>Pasaje</th>
                        <td>
                            <input type="text" name="valor_pasaje" id="valor_pasaje" class="form-control input-sm"  value="{{ $ruta->valor_pasaje }}"  >
                        </td>
                    </tr>
                    <tr>
                        <td colspan="2">
                            <button type="submit" class="btn btn-primary btn-block">
                                Actualizar
                            </button>
                        </td>
                    </tr>

                </table>
            </form>
        </div>
    </div>
    <a href="{{ route('ruta.index') }}" class="btn btn-info btn-block w-sm" >Atrás</a>
</div>

@endsection

resources/views/Ruta/index.blade.php
@extends('layouts.app')
@section('content')
<div class="col-md-8 col-md-offset-1">

    <div class="pull-left"><h3>Lista rutas</h3></div>
    <div class="pull-right">

        <a href="{{ route('ruta.create') }}"> 
            <button class="btn btn-info" >Añadir ruta</button>
        </a>

    </div>

    <div class="table-container">
        <table class="table table-bordered table-striped">
            <thead>
                <th>Id</th>
                <th>Ruta</th>
                <th>Origen</th>
                <th>Destino</th>
                <th>Bus</th>
                <th>Pasaje</th>

                <th colspan="2">Acciones</th>
            </thead>
            <tbody>
                @if($ruta->count())  
                    @foreach($ruta as $item)  
                    <tr>
                        <td>{{$item->id}}</td>
                        <td>{{$item->nombre_ruta}}</td>
                        <td>{{$item->origen_ciudad}}</td>
                        <td>{{$item->destino_ciudad}}</td>
                        <td>{{$item->bus_Id}}</td>
                        <td>{{$item->valor_pasaje}}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="{{action('RutaController@edit', $item->id)}}" ><span class="glyphicon glyphicon-pencil"></span></a>
                        </td>
                        <td>
                            <form action="{{action('RutaController@destroy', $item->id)}}" method="post">
                                {{csrf_field()}}
                                <input name="_method" type="hidden" value="DELETE">

                                <button class="btn btn-danger btn-xs" type="submit"><span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach 
                @else
                    <tr>
                        <td colspan="4">No hay registros !!</td>
                    </tr>
                @endif
            </tbody>
        </table>
       
    </div>
</div>


@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Home</div>

                <div class="panel-body">
                    <div class="col-md-4">
                        <a href="/cotizacion" target="_blank">
                            <button class="btn btn-primary">
                                <span class="glyphicon glyphicon-usd"></span>
                                Cotizar ruta
                            </button>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="/bus">
                            <button class="btn btn-primary">
                                <span class="glyphicon glyphicon-plane"></span>
                                Agregar Buses
                            </button>
                        </a>
                    </div>
                    <div class="col-md-4">
                        <a href="/ruta">
                            <button class="btn btn-primary">
                                <span class="glyphicon glyphicon-road"></span>
                                Agregar Rutas
                            </button>
                        </a>
                    </div>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'MYBUS LLC') }}</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/home') }}">
                        {{ config('app.name', 'MYBUS LLC') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
</body>
</html>

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="utf-8">

    <title>MY BUS LLC</title>
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>

    <h1>MY BUS LLC</h1>

	<div class="container-fluid" style="margin-top: 50px">

		@yield('content')
	</div>

<style type="text/css">
.table {
    border-top: 2px solid #ccc;
}
.w-sm {
    width: 100px;
}
*{
    font-family: 'Segoe UI',Frutiger,'Frutiger Linotype','Dejavu Sans','Helvetica Neue',Arial,sans-serif;
    font-size: 1.03em;
}
.alert, .btn {
    font-size: 1.02em !important;
}



</style>
</body>
</html>